// @generated by `cargo run -p conformance --bin generate`.
// DO NOT EDIT MANUALLY.

#[path = "gen/basic.rs"]
mod basic;
#[path = "gen/bindings_ext.rs"]
mod bindings_ext;
#[path = "gen/block_ext.rs"]
mod block_ext;
#[path = "gen/comparisons.rs"]
mod comparisons;
#[path = "gen/conversions.rs"]
mod conversions;
#[path = "gen/dynamic.rs"]
mod dynamic;
#[path = "gen/encoders_ext.rs"]
mod encoders_ext;
#[path = "gen/enums.rs"]
mod enums;
#[path = "gen/fields.rs"]
mod fields;
#[path = "gen/fp_math.rs"]
mod fp_math;
#[path = "gen/integer_math.rs"]
mod integer_math;
#[path = "gen/lists.rs"]
mod lists;
#[path = "gen/logic.rs"]
mod logic;
#[path = "gen/macros.rs"]
mod macros;
#[path = "gen/macros2.rs"]
mod macros2;
#[path = "gen/math_ext.rs"]
mod math_ext;
#[path = "gen/namespace.rs"]
mod namespace;
#[path = "gen/optionals.rs"]
mod optionals;
#[path = "gen/parse.rs"]
mod parse;
#[path = "gen/plumbing.rs"]
mod plumbing;
#[path = "gen/proto2.rs"]
mod proto2;
#[path = "gen/proto2_ext.rs"]
mod proto2_ext;
#[path = "gen/proto3.rs"]
mod proto3;
#[path = "gen/string.rs"]
mod string;
#[path = "gen/string_ext.rs"]
mod string_ext;
#[path = "gen/timestamps.rs"]
mod timestamps;
#[path = "gen/type_deduction.rs"]
mod type_deduction;
#[path = "gen/unknowns.rs"]
mod unknowns;
#[path = "gen/wrappers.rs"]
mod wrappers;
